version: "2"

services:

  mongo:
    image: mongo:3.4
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - link-retail


  myretail:
    build:
      context: ../myretail
    image: myretail-image
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    ports:
      - "8080:8080"
    networks:
      - link-retail

volumes:
  mongodata:

networks:
  link-retail: